### ISSUE TITLE
using deprecated size() function in SmartNotification.js

### ISSUE THREAD

**Issue by timvandesteeg** [griga/smartadmin-plugins#2]
var h=$(".SmallBox").size() gives an error in my application, when using jquery: "^3.1.1".

Can .size() be replaced with .length?

`var h=$(".SmallBox").size()` to
`var h=$(".SmallBox").length`

Fixed the issue for me

**Comment by griga** [comment]
Hi there! Thx for reporting this

fixed in [1.0.19 ](https://github.com/griga/smartadmin-plugins/commit/cd8a98f0f1c7be9b6eca213e0f7ee5b82b7e07d1)

**Comment by timvandesteeg** [comment]
perfect, thanks :)
